export type DesignSystemCategory = 'Foundations' | 'Primitives' | 'Cards' | 'Sections' | 'Layout'

export type DesignSystemEntry = {
  id: string
  name: string
  component: string
  category: DesignSystemCategory
  description: string
  variants: string[]
  props?: string[]
  usedIn: string[]
}

export const designSystemRegistry: DesignSystemEntry[] = [
  {
    id: 'foundation-color-paper',
    name: 'Color / Paper',
    component: 'Design token',
    category: 'Foundations',
    description: 'Warm paper background used across the public site.',
    variants: ['default'],
    usedIn: ['/'],
  },
  {
    id: 'foundation-color-ink',
    name: 'Color / Ink',
    component: 'Design token',
    category: 'Foundations',
    description: 'Primary near-black text and border color.',
    variants: ['default'],
    usedIn: ['/'],
  },
  {
    id: 'foundation-color-signal',
    name: 'Color / Signal Yellow',
    component: 'Design token',
    category: 'Foundations',
    description: 'Primary accent for calls to action and featured states.',
    variants: ['default'],
    usedIn: ['/'],
  },
  {
    id: 'foundation-color-sted-semantic-palette',
    name: 'Color / Sted Semantic Palette',
    component: 'Design tokens',
    category: 'Foundations',
    description: 'Muted printed colors for projects, tags, sources, states and knowledge types inside Sted.',
    variants: ['blue', 'green', 'pink', 'purple', 'red', 'cyan', 'gray', 'orange'],
    usedIn: ['/sted'],
  },
  {
    id: 'foundation-color-sted-bright-exploration',
    name: 'Color / Sted Bright Palette — Exploration',
    component: 'Design-system showcase only',
    category: 'Foundations',
    description: 'An unshipped, higher-energy comparison palette for future Sted exploration.',
    variants: ['primary', 'optional', 'comparison', 'context-demo'],
    usedIn: ['/design-system'],
  },
  {
    id: 'primitive-button-primary-yellow',
    name: 'Button / Primary Yellow',
    component: 'button',
    category: 'Primitives',
    description: 'High-contrast action button with mono uppercase label.',
    variants: ['default', 'hover', 'focus'],
    props: ['children', 'type'],
    usedIn: ['Hero', 'NewsletterSection'],
  },
  {
    id: 'primitive-label-mono',
    name: 'Label / Mono',
    component: 'p',
    category: 'Primitives',
    description: 'Terminal-style metadata label for section context.',
    variants: ['default'],
    usedIn: ['BuildLogs', 'WorkflowCards', 'FreeResources', 'ProjectsSection'],
  },
  {
    id: 'primitive-badge-status',
    name: 'Badge / Status',
    component: 'span',
    category: 'Primitives',
    description: 'Compact status marker for coming-soon and category states.',
    variants: ['coming-soon', 'category', 'affiliate'],
    usedIn: ['WorkflowCards', 'FreeResources', 'ProjectsSection'],
  },
  {
    id: 'card-workflow',
    name: 'Card / Workflow',
    component: 'WorkflowCards',
    category: 'Cards',
    description: 'Editorial card for practical AI workflow entries.',
    variants: ['default', 'featured-yellow'],
    props: ['number', 'title', 'description', 'tools', 'difficulty'],
    usedIn: ['/'],
  },
  {
    id: 'card-resource',
    name: 'Card / Resource Row',
    component: 'FreeResources',
    category: 'Cards',
    description: 'Two-column resource row with icon, metadata and external arrow.',
    variants: ['tool', 'course', 'article', 'hover-yellow'],
    props: ['name', 'description', 'category', 'href'],
    usedIn: ['/'],
  },
  {
    id: 'card-project',
    name: 'Card / Project',
    component: 'ProjectsSection',
    category: 'Cards',
    description: 'Building-in-public project card with status and icon tile.',
    variants: ['default', 'linked'],
    props: ['title', 'description', 'status', 'href'],
    usedIn: ['/'],
  },
  {
    id: 'section-hero-window',
    name: 'Section / Hero Window',
    component: 'Hero',
    category: 'Sections',
    description: 'Primary split hero with profile context and newsletter conversion.',
    variants: ['desktop', 'mobile'],
    usedIn: ['/'],
  },
  {
    id: 'sted-color-dot',
    name: 'Sted / Color Dot',
    component: 'StedColorDot',
    category: 'Primitives',
    description: 'Small semantic marker used to identify projects and content types at a glance.',
    variants: ['blue', 'green', 'pink', 'purple', 'red', 'cyan', 'gray', 'orange'],
    props: ['color', 'label'],
    usedIn: ['/sted'],
  },
  {
    id: 'sted-index-card',
    name: 'Sted / Index Card',
    component: 'StedIndexCard',
    category: 'Cards',
    description: 'Resurfaced knowledge card designed as a calm digital notebook annotation.',
    variants: ['featured', 'compact'],
    props: ['project', 'title', 'description', 'color'],
    usedIn: ['/sted'],
  },
  {
    id: 'sted-content-item',
    name: 'Sted / Content Item',
    component: 'StedContentItem',
    category: 'Cards',
    description: 'Archive item with content-type grammar, metadata and semantic color marker.',
    variants: ['image', 'link', 'article', 'note', 'conversation'],
    props: ['type', 'title', 'meta', 'color'],
    usedIn: ['/sted'],
  },
  {
    id: 'section-start-here',
    name: 'Section / Start Here',
    component: 'StartHere',
    category: 'Sections',
    description: 'Four-card orientation grid linking visitors to the main site pathways.',
    variants: ['four-column', 'two-column-mobile'],
    props: ['pillars'],
    usedIn: ['/'],
  },
  {
    id: 'section-newsletter-split',
    name: 'Section / Newsletter Split',
    component: 'NewsletterSection',
    category: 'Sections',
    description: 'Pinned newsletter entries paired with the subscription panel.',
    variants: ['desktop', 'stacked-mobile'],
    usedIn: ['/'],
  },
  {
    id: 'section-resource-table',
    name: 'Section / Resource Table',
    component: 'FreeResources',
    category: 'Sections',
    description: 'Filterable two-column table for tools, courses and articles.',
    variants: ['all', 'filtered'],
    usedIn: ['/'],
  },
]
